server:
  port: 8888
spring: 
  cloud:
    config:
      server:
        git:   #dirección repositorio remoto
          uri: https://github.com/bhodiDharma/configuracionServicios
        default-label: main